// AUTO-GENERATED by the demo-video skill — GAP MODE (TTS narration, 1.0x playback).
// Scene durations for the two screen-recording scenes come from ffprobe on the .mp4
// itself, so the video track is never hard-cut mid-action. Subtitle frames come from
// Whisper run on the actual audio; the text is corrected to what was really spoken.
export const FPS = 30;
export const W = 1920;
export const H = 1080;

export const PACING_MODE = "gap" as const;
export const PLAYBACK_RATE = 1.0;

// Kin's own tokens. See DECISIONS.md for why this video is not on a dark theme.
export const COLORS = {
  bg: "#17150f",
  paper: "#f7f3ea",
  paperRaised: "#fcfaf4",
  ink: "#17150f",
  ink2: "#5e5749",
  ink3: "#8a8273",
  rule: "#e0d8c6",
  accent: "#2a5140",
  accentWash: "rgba(42, 81, 64, 0.10)",
  flag: "#9b4a22",
};

export const CROSSFADE = 15;

// Real audio length from ffprobe. Drives the volume envelope, never the scene length.
export const AUDIO_DURATIONS = {
  "landing": 691,
  "judge": 2487,
  "close": 134
} as const;

// Screen-recording scenes: the video's own length. Animated cards: chosen.
export const SCENE_DURATIONS = {
  "open": 120,
  "landing": 821,
  "judge": 2760,
  "close": 240
} as const;

export const TOTAL_FRAMES = Object.values(SCENE_DURATIONS).reduce((a, b) => a + b, 0)
  - CROSSFADE * (Object.keys(SCENE_DURATIONS).length - 1);

export const AUDIO_FILES = {
  landing: "audio/landing.mp3",
  judge: "audio/judge.mp3",
  close: "audio/close.mp3",
} as const;

export const VIDEO_FILES = {
  landing: "video/landing.mp4",
  judge: "video/judge.mp4",
} as const;

// Must mirror the TransitionSeries order exactly — Subtitles.tsx walks this to build
// global frame offsets, and any divergence desyncs every caption after it.
export const SCENE_ORDER = ["open", "landing", "judge", "close"] as const;

export const SUBTITLES = {
  "landing": [
    {
      text: "When someone dies, one person has to tell twenty or thirty organisations.",
      start: 0,
      end: 130
    },
    {
      text: "Five are banks.",
      start: 130,
      end: 166
    },
    {
      text: "The rest are the phone carrier, the gym, the storage unit.",
      start: 166,
      end: 259
    },
    {
      text: "Each wants something different, and most will not say what until you have waited on hold.",
      start: 259,
      end: 394
    },
    {
      text: "Nearly every product in this space assumes you can email a bank about a death.",
      start: 394,
      end: 523
    },
    {
      text: "We read their own pages instead. Of seven organisations, exactly one accepts email.",
      start: 523,
      end: 689
    }
  ],
  "judge": [
    {
      text: "This is running now, with one input: the words Wells Fargo.",
      start: 0,
      end: 111
    },
    {
      text: "Firecrawl finds their own page, because hard-coded links rot.",
      start: 111,
      end: 219
    },
    {
      text: "Of nine we tried by hand,",
      start: 219,
      end: 273
    },
    {
      text: "four were wrong and two refused to load.",
      start: 273,
      end: 342
    },
    {
      text: "Nothing on that list of steps is on a timer.",
      start: 342,
      end: 426
    },
    {
      text: "Each line strikes through only when that step really finishes.",
      start: 426,
      end: 528
    },
    {
      text: "Then the model reads the page it actually fetched.",
      start: 528,
      end: 612
    },
    {
      text: "The middle line of this address is the one that matters.",
      start: 612,
      end: 702
    },
    {
      text: "It carries an internal mail-stop code.",
      start: 702,
      end: 777
    },
    {
      text: "No model knows that string, and it appears nowhere in our code, which is the point.",
      start: 777,
      end: 903
    },
    {
      text: "Every contact detail is checked back against the page before it is stored.",
      start: 903,
      end: 1011
    },
    {
      text: "And anything the model produced that is not literally on that page is dropped and named.",
      start: 1011,
      end: 1131
    },
    {
      text: "On this run, nothing was dropped.",
      start: 1131,
      end: 1194
    },
    {
      text: "Wells Fargo will not take a death notification by email.",
      start: 1194,
      end: 1293
    },
    {
      text: "Neither will Chase.",
      start: 1293,
      end: 1332
    },
    {
      text: "We read their pages rather than assuming.",
      start: 1332,
      end: 1404
    },
    {
      text: "So Kin refuses to offer a send button here, and produces the exact postal packet instead.",
      start: 1404,
      end: 1566
    },
    {
      text: "Detecting the channel is the feature, not a limitation we route around.",
      start: 1566,
      end: 1692
    },
    {
      text: "Where an organisation does accept email,",
      start: 1692,
      end: 1767
    },
    {
      text: "AgentMail writes the letter from their own stated requirements and catches the reply on the same card.",
      start: 1767,
      end: 1914
    },
    {
      text: "Nothing is ever sent without a person approving it.",
      start: 1914,
      end: 2007
    },
    {
      text: "And the page says plainly what is not true yet.",
      start: 2007,
      end: 2088
    },
    {
      text: "That send path has not been run end to end,",
      start: 2088,
      end: 2169
    },
    {
      text: "because no organisation we have tested so far accepts email.",
      start: 2169,
      end: 2265
    },
    {
      text: "Spotify and Netflix publish no bereavement process at all.",
      start: 2265,
      end: 2352
    },
    {
      text: "So the honest result there is a flagged third-party source,",
      start: 2352,
      end: 2436
    },
    {
      text: "not an invented official one.",
      start: 2436,
      end: 2484
    }
  ],
  "close": [
    {
      text: "Built on Convex. Every step you just watched ran live, in one take.",
      start: 0,
      end: 120
    }
  ]
} as const;

export const SOCIAL_FPS = 30;
export const SOCIAL_W = 1080;
export const SOCIAL_H = 1920;
export const SOCIAL_DURATION = 11 * FPS;
